# Generated by Django 2.1 on 2020-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
